



export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';


export const SET_CURRENT_SITUATION = 'SET_CURRENT_SITUATION';
export const SET_ROOM_FOR_IMPROVEMENT = 'SET_ROOM_FOR_IMPROVEMENT';
export const SET_MEASURE = 'SET_MEASURE';
export const SET_RISKS = 'SET_RISKS';

